[phases.setup]
nixPkgs = ["nodejs", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "npm install",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "npm run start:hybrid"

[variables]
PYTHONPATH = "/app"
PYTHON_SERVICE_URL = "http://localhost:8000"
NODE_ENV = "production"
