name: Frontend CI/CD - Development

on:
  push:
    branches: [dev]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-dev.yml'
  pull_request:
    branches: [dev]
    paths:
      - 'frontend/**'

env:
  NODE_VERSION: '20.x'

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Build Application
        run: npm run build
        env:
          VITE_API_URL: https://api-dev.mocktstudio.com.br

      - name: Run Tests
        run: npm test --if-present
        env:
          CI: true

  auto-promote-to-homol:
    name: Auto-promote to Homol
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request to Homol
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev
          base: homol
          title: "🚀 Auto-promote Frontend DEV → HOMOL"
          body: |
            ## ✅ Frontend DEV passou em todos os testes!

            ### Testes executados:
            - ✅ Build Vite
            - ✅ Unit Tests

            ### Próximos passos:
            1. Review automático da pipeline HOMOL
            2. Lighthouse Performance Audit
            3. Se passar → Auto-promote para MAIN

            **Criado automaticamente pela pipeline CI/CD**
          labels: |
            auto-promote
            frontend
            homol
