name: Frontend CI/CD - Development

on:
  push:
    branches: [dev]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-dev.yml'
  pull_request:
    branches: [dev]
    paths:
      - 'frontend/**'

env:
  NODE_VERSION: '20.x'

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint --if-present

      - name: Run Type Check
        run: npm run type-check --if-present

      - name: Build Application
        run: npm run build
        env:
          VITE_API_URL: https://api-dev.mocktstudio.com.br

      - name: Run Tests
        run: npm test --if-present
        env:
          CI: true

  deploy-dev:
    name: Deploy to Railway (Dev)
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Railway
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: fe-financeServer-dev
        env:
          RAILWAY_ENVIRONMENT: development
          VITE_API_URL: https://api-dev.mocktstudio.com.br
