name: Frontend CI/CD - Development

on:
  push:
    branches: [dev]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-dev.yml'
  pull_request:
    branches: [dev]
    paths:
      - 'frontend/**'

env:
  NODE_VERSION: '20.x'

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Build Application
        run: npm run build
        env:
          VITE_API_URL: https://api-dev.mocktstudio.com.br

      - name: Run Tests
        run: npm test --if-present
        env:
          CI: true

  auto-promote-to-homol:
    name: Auto-promote to Homol
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request to Homol
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if PR already exists
          existing_pr=$(gh pr list --base homol --head dev --state open --json number --jq '.[0].number' || echo "")

          if [ -z "$existing_pr" ]; then
            gh pr create \
              --base homol \
              --head dev \
              --title "🚀 Auto-promote Frontend DEV → HOMOL" \
              --body "## ✅ Frontend DEV passou em todos os testes!

          ### Testes executados:
          - ✅ Build Vite
          - ✅ Unit Tests

          ### Próximos passos:
          1. Review automático da pipeline HOMOL
          2. Lighthouse Performance Audit
          3. Se passar → Auto-promote para MAIN

          **Criado automaticamente pela pipeline CI/CD**"
            echo "✅ PR created successfully!"
          else
            echo "ℹ️ PR #$existing_pr already exists"
          fi
