name: Frontend CI/CD - Development

on:
  push:
    branches: [dev]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-dev.yml'
  pull_request:
    branches: [dev]
    paths:
      - 'frontend/**'

env:
  NODE_VERSION: '20.x'

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Build Application
        run: npm run build
        env:
          VITE_API_URL: https://api-dev.mocktstudio.com.br

      - name: Run Tests
        run: npm test --if-present
        env:
          CI: true
